### ISSUE TITLE
smash case

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#319]
* For every AltLabel in every point not matching a primary waypoint label (most of the time) in every valid region/highway combo in every .list, we [smash case](http://www.catb.org/jargon/html/S/smash-case.html) 3 times:
  1. .lower() to compare to list labels
  2. .upper() to add to `labels_in_use`
  3. .upper() to check membership in `unused_alt_labels` & remove/erase

  Removing this redundancy can gain us some efficiency and clean up the code pending #278.
<br>

* Similarly, for every valid region/highway combo, we smash case on all `alt_route_names` until we match `route_entry`.

  Removing this redundancy can gain us some efficiency and clean up the code pending #230.
<br>

To be addressed in tandem with #316.
* [x] Handle that first and squash commits.

### ToDo:
* [x] .upper() all `alt_labels` at once during Waypoint construction
* [x] .strip('+') here too
* [x] populate unused alt labels: don't smash case or .strip('+') anymore
* [x] clean up `alt_labels` handling in TravelerList ctor
* [x] .upper() all `alt_route_names` at once during Route construction
* [x] don't smash case in TravelerList ctor (one line above `Note: deprecated route name`)
* [x] clean up DUPLICATE_LABEL datacheck
* [x] similarly .lower() `root` during Route construction
* [x] make sure not lowered again during `root_hash` insertion
* [x] .lower() all `roots` at once during ConnectedRoute construction
* [x] change .lower() to .upper() as appropriate (not roots) globally

---
**Similarly:**
Another idea that may help speed up .list processing:
* [ ] Store an `upper_label` pre-stripped of leading `+` or `*` characters for each Waypoint upon construction, to avoid having to repeat this process every time we iterate through a route for a valid region/highway combo.
  **Maybe** this is a bit rich for my blood though, if the eventual idea is to implement #278.

**Comment by yakra** [comment]
Theoretical C++ speedup *Reading waypoints for all routes.*

**Comment by yakra** [comment]
**Oh crap.** Just realized this will break nmpfps.log.

**Comment by jteresco** [comment]
If I'm understanding the issue, could we just upcase or downcase the existing nmpfps.log when such a change would go live?

**Comment by yakra** [comment]
I suppose we could, but I've already worked around that.
It was just something I hadn't planned for, but thankfully the fix was very simple.

**Comment by yakra** [comment]
No diffs Python <-> C++.
Only old <-> new diff is DUPLICATE_LABEL entries in datacheck.log are caps now, rather than lower case.
siteupdate.py just ran to completion on noreaster.
Python speed comparison is underway on lab1, just > 20% done.
Time to commit, squash, and start the C++ speed tests!

**Comment by yakra** [comment]
Python: Time spent *Processing traveler list files* on lab1 is down by just over a third.

**Comment by yakra** [comment]
squashed commits on BiggaTomato:
fcc7b5542f821bb5b32e99d7e465ffc01679c27d
a42ba98b73ce1ca6fe0f29df72ebfa6505ccec42
d08eb61d533f1aa696817cfda6ab8ed9bed00d5b
