### ISSUE TITLE
C++ site update to production

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#375]
I'd like to work toward using the C++ version of the site update program.  @yakra are you confident in the threaded version's readiness for production site updates?

I think that moving to the C++ program its inherent efficiency advantages over Python and the ability to do some meaningful multithreading, in conjunction with the addition of SSDs and/or using memory filesystem could really speed the whole process significantly.

**Comment by jteresco** [comment]
A first question on this: what C++ compiler and version do you use when you build it for Linux?  

g++ 9.3.0 compiles and links, but I get a run time error on noreaster:

<pre>
ld-elf.so.1: /usr/local/lib/gcc5/libstdc++.so.6: version GLIBCXX_3.4.22 required by /tm-tmpfs/travelmapping/DataProcessing/siteupdate/cplusplus/a.out not found
</pre>

clang 10.0.1 doesn't compile it successfully, being unhappy with the use of subscript operators.

**Comment by yakra** [comment]
> @yakra are you confident in the threaded version's readiness for production site updates?

Other than #281 (just cosmetic, an easy fix for a clean readable siteupdate.log), yes! I believe I have mutexes around everything else I need to, and even [some things I don't](https://github.com/TravelMapping/DataProcessing/issues/366#issuecomment-742980436). [The last crashes & glitches](https://github.com/TravelMapping/DataProcessing/issues/323) were fixed in #333. Since then I've run siteupdate many thousands of times during speed tests with no [other known issues](https://github.com/TravelMapping/DataProcessing/issues?q=is%3Aopen+label%3Abug++label%3AC%2B%2B+) except #327, which "is super obscure, and not too big a deal in the real world". It shouldn't hold the C++ version back from going live, and may become moot anyway once multi-threaded HighwayGraph setup enters the picture.

> I think that moving to the C++ program its inherent efficiency advantages over Python and the ability to do some meaningful multithreading, in conjunction with the addition of SSDs and/or using memory filesystem could really speed the whole process significantly.

No need for super-fast storage subsystems. NMP_merged files take about 0.5s on lab2. Unsure what the exact bottleneck is here, but everything else is CPU/memory bound. Graph files are written to disk at less MBps than nmp_merged.

> A first question on this: what C++ compiler and version do you use when you build it for Linux?
>
> g++ 9.3.0 compiles and links, but I get a run time error on noreaster:
>
> <pre>
> ld-elf.so.1: /usr/local/lib/gcc5/libstdc++.so.6: version GLIBCXX_3.4.22 required by /tm-tmpfs/travelmapping/DataProcessing/siteupdate/cplusplus/a.out not found
> </pre>

[Yup. Same message I got.](https://forum.travelmapping.net/index.php?topic=3603)
In the immediate term, you can disable threading by commenting out
https://github.com/TravelMapping/DataProcessing/blob/deead7ac837e9463f5f64d3008c0b9ff0c91fdf7/siteupdate/cplusplus/enable_threading.cpp#L1

What versions do I use?

box(es) | ver
-- | --
lab1, lab2 | g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
lab3 | g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
BiggaTomato | g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
lab1.5, epoch | g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

> clang 10.0.1 doesn't compile it successfully, being unhappy with the use of subscript operators.

I'm new to clang *\*checks wikipedia article\**.
Interesting. What does it choke on?
I'm using C++11, so on my linux boxes I use `g++ siteupdate.cpp -std=c++11 -pthread -o siteupdate`
On noreaster,  we don't even need those switches; once I comment out enable_threading.cpp, just `g++ siteupdate.cpp -o siteupdate` does the trick.

**Comment by jteresco** [comment]
All right, good.  We can think about moving in this direction.

As far as clang, it gives pages of errors, many of which look like this:

<pre>
In file included from siteupdate.cpp:72:
./classes/DatacheckEntry.cpp:69:14: error: type 'std::array<std::string, 6>' (aka 'array<basic_string<char,
      char_traits<char>, allocator<char> >, 6>') does not provide a subscript operator
                if (fpentry[0] != route->root)  return 0;
                    ~~~~~~~^~
</pre>

I don't think it really matters to me if we compile with clang, g++, or something else, so I wouldn't consider that a high priority.

Here's a new Issue about getting this compiled and running with pthreads support: #376

**Comment by yakra** [comment]
My working tree on noreaster has (for the moment) some changes to 4b9c7198025f9dcb3a6d3a14c9f816b78018530a to enable compilation with clang++.
siteupdateST compiles fine *with g++*, and runs to completion.
With clang, siteupdate & siteupdateST crash when `Sorting colocation lists`. Somehow, there's an invalid pointer for `Waypoint::colocated`. Strangely, always at `la.la1088 LA36 (30.433911,-89.91344)`, even when multi-threaded.

> Sorting WaypointQuadtree at (30.41015625,-90) to (30.5859375,-89.6484375) contains 37 waypoints
Points sorted. Sorting colocation lists...
...
3	la.la0036 LA1088 (30.433911,-89.91344)
	0x**9**12e2a0e0
...
19	la.la1088 LA36 (30.433911,-89.91344)
	0x12e2a0e0

Even though this memory is allocated on the heap, I'm seeing consistent values for all `Waypoint::colocated` locations in the quadtree node, (No problem, that helps!)
What's really weird here is how the 2 addresses above are the same except for the missing high-order nibble.

Even if I comment out `Sorting colocation lists`, there's still a crash when `Setting up for graphs of highway data`. No surprise here, as we'd still encounter the invalid `Waypoint::colocated` pointer and attempt to dereference it.

* How does this happen?
* How early in the process?

This will take a pretty deep dive, one that I don't have the attention span for right yet.
Two [other](https://github.com/TravelMapping/DataProcessing/issues/397) [projects](https://github.com/yakra/DataProcessing/issues/147) have each yielded an unmanageably large number of experimental branches. I want to play arborist, prune extraneous branches, and merge changes back into master before proceeding.

**Comment by yakra** [comment]
**The bug above is reproducible with**
`HighwayData @ d5d320322c2e46a722299b6bd1c8a6e25526fcbd`
`UserData @ 3491f1b4e5dbe11a4d470ed67257bb929442af22`

Starting to get the impression it's related to a specific point (or range rather) in memory.
* [ ] To be more certain, what I really want is the address *of* `colocated` within the Waypoint object, not the address stored *in* the pointer.

[Checking out an older HighwayData commit](https://github.com/TravelMapping/DataProcessing/issues/376#issuecomment-765125024) to cause all the waypoint objects (and thus that particular colocation list pointer) to be stored in different places seems to do the trick. The pointer stays valid and siteupdate runs to completion.

So what's the deal? **Is there bad RAM?** Why do we lose exactly 0x900000000, with two ones turning to zeros?
* [ ] I'll take a closer look at where exactly that colocation list pointer is itself stored...

**Comment by yakra** [comment]
## What memory locations?
> I'll take a closer look at where exactly that colocation list pointer is itself stored...

`0x912d86208` consistently with siteupdateST.
`0x914848208 - 0x914898208` with 7 trials of siteupdate -t 1.
`0x919287768 - 0x91a957428` with 8 trials of siteupdate -t 4.

Doing a `git bisect` from `HighwayData @ 27a6254` which ran OK, the crash first appears...
* with siteupdateST at `HighwayData @ 60d774f`. Right when `Waypoint::colocated` locations are first starting to edge over `0x900000000`.
`0x900080048` fails.
* with siteupdate -t 4 at **TBD**

***paste siteupdate.log debug text here***

---

## When does it happen?
**siteupdate.cpp**
```c++
      #ifdef threading_enabled
	// stuff that never happens in siteupdateST because of the #ifdef
      #else
	for (HighwaySystem* h : highway_systems)
	{	std::cout << h->systemname << std::flush;
		bool usa_flag = h->country->first == "USA";
		for (Route* r : h->route_list)
			r->read_wpt(&all_waypoints, &el, args.highwaydatapath+"/hwy_data", usa_flag, &all_wpt_files);
		std::cout << "!" << std::endl;
	}
      #endif

	// DEBUG //
	list<Waypoint*> schmist = all_waypoints.point_list();
	schmist.sort();
	ofstream schmile("schmile");
	for (Waypoint *w : schmist)
	{	schmile << &w->colocated << '\t';
		schmile << w->colocated << '\t';
		if (!w->colocated) schmile << '\t';
		schmile << w->str() << std::endl;
	}

	cout << et.et() << "Sorting waypoints in Quadtree." << endl;
```

# TODO more detail!

**Comment by yakra** [comment]
Updating the repos to newer commits...
`HD @ e21d08b17773ae508b858220d23c6c4b9d830165`
`UD @ c9da0fa30ee592cad2bd9ee7c323b27c057093af`
...siteupdate & siteupdateST crash when reading ausvictd.csv.
This file only dates to `Sun Jan 10 18:05:50 2021 +0000` per `git log`, so it's unrelated to crashes happening with June's data....
* ...that is, if this is a HighwayData problem.
* This could be a new, different symptom of an underlying DataProcessing bug...
  * An as-yet-unknown pointer gets scrambled when first *Reading systems list*.
  * When performing datachecks, we write through this pointer...
  * ...and wacky antics ensue, as described in previous posts.

This problem persists even when compiled with g++ on noreaster. Does it also happen on...
* [ ] Ubuntu?
* [ ] CentOS?

**Comment by yakra** [comment]
New issue #402 for the chopped routes CSV bug.
It should be addressed before any further investigation into the `colocated` pointer bug.

**Comment by yakra** [comment]
#403 closes #402.
The issue above remains.
I'll put this back on the backburner while tying up those other 2 projects.

**Comment by yakra** [comment]
The problem is somewhere in the single-point Datachecks.

**Comment by yakra** [comment]
* [x] Everything after `all_waypoints->insert(w, 1);` for the remainder of `Route::read_wpt` commented out. Even `delete[] wptdata`. Still crashes.
* [ ] If it's something in the code, it's in `WaypointQuadtree::insert`...

Home come the pointer is fine if located < 0x900000000, but gets mangled if located > 0x900000000?
(Worth noting that the g++ version doesn't store Waypoints in this memory range -- more 0x84####### ballpark. Could this be why it doesn't crash?)

**Comment by yakra** [comment]
>  If it's something in the code, it's in `WaypointQuadtree::insert`...

...Or is it?
In Waypoint.h, moving `std::list<Waypoint*> *colocated;` earlier in the class definition, the 2nd item after only `Route *route;`, makes the problem go away. Was it a failure of a pointer to fall right on an 8-byte address, causing wacky antics?
* [ ] Does `sizeof(Waypoint)` differ between clang & g++?
* [ ] Does `sizeof(Waypoint)` change when the header is rearranged?

**Comment by yakra** [comment]
A full pass thru siteupdate with [valgrind](https://www.valgrind.org/) will be worthwhile.
It reported there were some errors / things to look at, almost all of which I glossed over in the rush to solve #443.
It'll be good to see what may be lurking in the shadows. And maybe my memory management (and whatever else) is a bit sloppy.

**Comment by jteresco** [comment]
"[your] memory management" -> "C++'s memory management"

**Comment by yakra** [comment]
Heh. My memory mgmt too, considering what I've done (and not done) knowing the language's shortcomings.
Like, take all the
```C++
foo* bar = new foo;
	   // deleted on termination of program
```
littered throughout the source. I explicitly `delete` very little of it. Waypoints, HighwaySegments, HighwayGraph components, TravelerLists? I wait till the program ends, and System Monitor says I magically get all those gigs of space back, and my RAM use is back where it was before I ran siteupdate. (Don't know if that's a compiler thing, or an OS thing, or *how* that works...)

Looks like Valgrind has something to say about all this.
What I'm doing may not exactly be best practice. :)

**Comment by yakra** [comment]
> Another minor surprise I didn't look into was something about a branch relying on uninitialized data. Edge construction or compression IIRC. A bit of a surprise; I'd think I'd notice some effects...

It happens exactly once, for US19TrkPit.
https://github.com/TravelMapping/DataProcessing/blob/4d988b326b2c2069a71b43177c4c1721859ac0dd/siteupdate/cplusplus/classes/GraphGeneration/HGEdge.cpp#L23-L35
`format` needs to be initialized before the destructor is called.

We get 3 errors when the destructor calls `detach`.
The branch itself is no-harm-no-foul: we either do or don't search the endpoint's adjacency lists for `this`, and find nothing.
Then one more error: half the time we'll neglect to delete the `s_written` array, and leak 1 byte per thread.

**Comment by yakra** [comment]
> Then one more error: half the time we'll neglect to delete the `s_written` array, and leak 1 byte per thread.

Nope. We neglect to delete it *all the time*, even with the fix in place, leaking 1 byte per thread *per edge*.
(As of HwyData@0a07f53 & UserData@412dfaf2, that's 932211 bytes per thread.)

The destructor calls `detach`, which zeros out `format`, thus `if (format & simple) delete[] s_written;` never happens.

Best to delete `s_written` when the edge is detached from the simple graph.
Similarly deleting `c_written` and `t_written` upon `detach` avoids having them hanging around being useless until the edge is deleted.
This eliminates the need for an explicitly defined `HGedge` destructor altogether. Cleaner code for the win.

**Better yet?**
Separate simple/collapsed/traveled arrays waste RAM when only one bit of each element is needed.
Instead, have one single `written` array & use a bitmask. Adaptation should be easy; most of the heavy lifting is already done.
* Losing 2 pointers saves 16 bytes per edge.
* For the arrays themselves, we save 1 (`s_written` is only allocated for edges in the simple graph) or 2 bytes per edge per thread.
* At the aforementioned commits, that's 14,915,376 B  & 1,754,407 B per thread respectively. Just under 16 MiB at 1 thread.

qty | format | description
-- | -- | --
299120 | 1 | simple only
26 | 2 | collapsed only
0 | 3 | simple + collapsed<br>These should never exist. Any vertices collapsed for the<br>traveled graph are also collapsed for the collapsed graph.
15 | 4 | traveled only
38 | 5 | simple + traveled
109974 | 6 | collapsed + traveled
523038 | 7 | simple + collapsed + traveled<br>Everything built by the first constructor starts out as one of these.
**932211** | **Total** | all edges in all master graphs

**Comment by jteresco** [comment]
We're there!
