### ISSUE TITLE
organize TODO simplification examples

### ISSUE THREAD

**Issue by yakra** [TravelMapping/DataProcessing#427]
* [x] move from canonical_waypoint_name.cpp to appropriate files (+ Python equivalent)
* [x] group related examples together
* [x] examples from #90
* [x] separate from adjacent comments with whitespace
