### ISSUE TITLE
Invalid links in updates.csv

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/DataProcessing#62]
Moving from https://github.com/TravelMapping/Web/issues/239 to this repository as a data processing issue.

**Comment by yakra** [comment]
@michihdeu's original comment:
> Root links of updates.csv should be automatically checked and invalid links should be output in a log file linked on the site.
>
> See https://github.com/TravelMapping/HighwayData/commit/8dd95d17237ccd7ef719b9db7bd5d9314b166e28#commitcomment-24855860

**Comment by yakra** [comment]
The signal-to-noise ratio would be hurt by links, valid at the time the original updates entry was made, to routes that were later deleted. For example:
```
2019-02-27;Ireland;R942;irl.r939;Route deleted (renumbered R939)
...
2018-06-07;Ireland;R942;irl.r942;New Route
```

Adding these to the Datacheck entries (`irl.r942;[updates.csv];;;INVALID_ROOT;2018-06-07` syntax?) to mark as FPs would mean reworking the `DatacheckEntry` class to store a root string rather than a `Route` object.

**Comment by michihdeu** [comment]
Again: https://github.com/TravelMapping/HighwayData/pull/4399#issuecomment-745825159
It also happens to me quite often and can only check it after the next site update....

> The signal-to-noise ratio would be hurt by links, valid at the time the original updates entry was made, to routes that were later deleted.

we could deal with it like with #189 where we output the most recent entries first.
we could also limit it to one or two months.

I think it should also be output in `datacheck.sh`

**Comment by yakra** [comment]
@michihdeu [wrote](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-745834818):
> we could deal with it like with #189 where we output the most recent entries first.
we could also limit it to one or two months.

I'm thinking, limit it to dates >= the last site update (a similar approach to #189).
Now that [repo head info is included](https://github.com/TravelMapping/DataProcessing/pull/312) in [siteupdate.log](https://travelmapping.net/logs/siteupdate.log), we can have localupdate.sh & datacheck.sh grab the last update date
```sh
git show --pretty=%cs `head -n 1 /home/www/tm/logs/siteupdate.log | cut -f3 -d' '`
```
and pass it on to siteupdate, I'm thinking via a new commandline switch.

**Comment by michihdeu** [comment]
@yakra I guess that @jteresco has no thoughts on this?

**Comment by jteresco** [comment]
No, I'd say whatever the two of you come up with as a solution, or if you decide to leave things as-is, is fine with me.

**Comment by jteresco** [comment]
Something worth pursing further?

**Comment by michihdeu** [comment]
> Something worth pursing further?

Yes! It often happens to me* that the update entry link is incorrect (copy&paste error, typos or missing `abbreviation`)

*I usually check all European links and also often face the same mistake from @si404 and @rmihailucian

**Comment by michihdeu** [comment]
Just another invalid link from last night: https://github.com/TravelMapping/HighwayData/pull/6253#issuecomment-1368373556
It's the most common situation where a deleted route got the now deprecated link instead of a blank entry.

**Comment by michihdeu** [comment]
The invalid links directly bother vanilla users when they want to update their list files.

Errors do often happen + vanilla users are often directly affected = high priority?

**Comment by jteresco** [comment]
A new thought that's probably more worth its own Issue(s) here and/or in the Web repository: a link to the commit for changed .wpt files so people can see the diffs of the changes.

**Comment by michihdeu** [comment]
> A new thought that's probably more worth its own Issue(s) here and/or in the Web repository: a link to the commit for changed .wpt files so people can see the diffs of the changes.

I often update my list file by checking the commit diffs. Just today with the [Polish update](https://github.com/TravelMapping/HighwayData/pull/6253).... However, I don't see an automated way to directly show the right diffs. Is a simple reference to the wpt file benefit enough for vanilla users? And yes, it would likely be a web directory issue.

**Comment by yakra** [comment]
> The invalid links directly bother vanilla users when they want to update their list files.

> It's the most common situation where a deleted route got the now deprecated link instead of a blank entry.

I don't see this as causing very much confusion. If a route is listed as deleted, and the link brings up an empty HD page, the user should be able to figure out what happened. They may only click the link accidentally, in auto-pilot or not thinking, etc.

(There's also potential for [valid but wrong](https://github.com/TravelMapping/HighwayData/pull/4844) roots, or [roots missing entirely](https://github.com/TravelMapping/HighwayData/pull/5384). Not much can be done here, but that's arguably outside the scope of this issue (**invalid links**) anyway. So, just leaving these links here.)

@yakra [wrote](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-471900566):
> The signal-to-noise ratio would be hurt by links, valid at the time the original updates entry was made, to routes that were later deleted.

@michihdeu [wrote](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-745834818):
> we could also limit it to one or two months.

Whatever threshold we pick, there's a chance something could come in under it. [A couple AB201 segments lasted only 8 days.](https://github.com/TravelMapping/HighwayData/commits/master/hwy_data/_systems/canab.csv)
This means an `ErrorList` error is out, as routes updated & then deleted within that window, with legit updates.csv entries, would halt the siteupdate process.
Including entries on the datacheck page would mean some pretty big changes to the Datacheck class on the DataProcessing side, and to datacheck.php on the Web side, stuff I'm not sure we'd want to do.

> I think it should also be output in `datacheck.sh`

Looks like the thing to do would be to print an error message to the terminal without adding to `ErrorList`.

Overall I think there are too many probems here. While I do see the original issue as a minor inconvenience, but just not a deal-breaker.
Meanwhile, @Markkos1992 is pretty good at spotting typos. :)

---

@jteresco [wrote](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-1368494995):
> A new thought that's probably more worth its own Issue(s) here and/or in the Web repository: a link to the commit for changed .wpt files so people can see the diffs of the changes.

@michihdeu [wrote](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-1368505332):
> I don't see an automated way to directly show the right diffs.

This. Often, the .wpt change is in a separate commit from the updates entry. Sometimes, even a separate pull request.

**Comment by yakra** [comment]
> I'd like to have something I can directly check prior to submitting the pull request. Maybe a simple log file on noreaster I can check?
Simply output all invalid links.

Did a quick implementation. 5 new lines of code. Easy.
Rather than just the root, it writes the entire line as it exists in updates.csv.
Makes it more human-readable to see the whole update in context, and there may be multiple entries for a given root.
Plus, keeping the date at the start of the line lets us do some nifty shell scripting. More on this below.

I see several errors in my regions right away.

>  That log would also be on the production server after the official site update so that every contributor can check it if desired.

Yes.

> I can ignore (historical) broken links **from other contributors**.

My first thought was to filter `updatesinvalidroots.log` based on a custom "my regions" file as part of the "dashboard" script I've mentioned on the forum at times.
Problem with that is, if I typo `ms.i095`  for `ma.i095`, that won't show up in my results because MS isn't one of my regions.
Other ways of filtering by contributor look too unreliable and error-prone. :(

> I can ignore **(historical)** broken links from ~other contributors~ everybody.

This'll work better.
We can filter for just the new stuff, newer than Jim's master copy used to update the site.

## How to do that?

The simplest way for now is:
```sh
/fast/tm/datacheck
grep ^2025 logs/updatesinvalidroots.log
```
This will work till whichever comes first, 2026 or any false positives entering the data this year.

Longer term, to add to siteupdate.sh itself, something *sorta* like
```sh
csvdate=$(cd ~terescoj/travelmapping/HighwayData/; git log --pretty=%as -n 1 updates.csv)
while read line; do [[ "$csvdate" < "$line" ]] && echo "$line"; done < logs/updatesinvalidroots.log
```
but still need to nail down a few specifics.

---

@michihdeu & @jteresco, shall I open a pull request for just `updatesinvalidroots.log` itself right away, and we can get siteupdate.sh sorted afterward?

Also: **filename?**
It's kinda verbose.
Continued using "alloneword.log" style naming; as all log files do so thus far -- tm-master.nmp is an .nmp file. :)
Could go with "updates-invalid-roots.log" -- if someone were to parse it as "updates-in-valid-roots.log" that'd be confusing.
Or, **any other ideas?**

**Comment by yakra** [comment]
## For the existing entries...
A shell script to look for "false positives" -- roots that were valid when first added, but later deleted, renamed/redesignated, or merged
```sh
e=$(echo -e '\e')
green_keywords='[Dd]eleted|[Mm]erged|[Rr]edesignated|[Rr]enamed'
roots=$(cut -f4 -d';' logs/updatesinvalidroots.log | sort | uniq)
count=0; total=$(echo "$roots" | wc -w | tr -d ' '); \
for r in $roots; do
  clear
  echo -e $((++count))/$total": $r\n"
  for R in $(grep "^.*;.*;.*;$r;.*$" ~terescoj/travelmapping/HighwayData/updates.csv \
  | cut -f3 -d';' | sort | uniq | tr ' ' '%'); do
    R=$(echo "$R" | sed -r -e 's~\(~(*~g' -e 's~%~ *~g' -e 's~\)~)*~g' -e 's~^([A-Z]+)([0-9]+)~\1 *\2~')
    grep -m 1 "^.*;.*;$R;.*;.*$" ~terescoj/travelmapping/HighwayData/updates.csv \
    | sed -r -e "s~;$r;~;$e[1m$e[4m$e[31m$r$e[0m;~" -e "s~($green_keywords)~$e[1m$e[4m$e[32m\1$e[0m~g"
  done
  echo -n '>>> PRESS ENTER <<<'
  read OK
done
```
It has its issues, but TLDR.

The 1st result is something I need to fix:
> 1/621: ab.ab043x
> 
> 2020-09-24;(Canada) Alberta;AB 43X;*`ab.ab043x`*;**Deleted**. Now part of relocated AB 43.

1st one for @michihdeu's regions:
> 18/621: aut.l5504
> 
> 2023-04-22;Austria;L550-4;*`aut.l5504`*;Route relocated from Linzer Straße and Hauptstraße, and onto Pyhrnstraße in Windischgarsten from Hauptstraße/Pyhrnstraße junction to B138

Is this a genuine error in need of a fix? Deleted without an updates entry?
Could be something wrong with my script, or something else.

Let me know if you want me to paste in anything else I find in your regions .

**Comment by michihdeu** [comment]
> Is this a genuine error in need of a fix? Deleted without an updates entry?

aut.l5504 --> aut.l**0**5504

> Let me know if you want me to paste in anything else I find in your regions .

Sure 😃

**Comment by michihdeu** [comment]
I think that `invalidupdatesroots.log` (+ `invalidsystemupdatesroots.log` ?) would be fine. Just like unmatchedXXX, unprocessedXXX, unusedXXX

**Comment by yakra** [comment]
## Updated shell script
* Improved s/n ratio; skips over likely FPs without displaying
* "Expand" option for more info

**ToDo**
* [ ] Assumes updates.csv is sorted newest-first, but this might not cause negative effects.

## Find & format info, either expanded or not

**bash flavored**
```sh
get_res () {
    for R in $routes; do
      R=$(echo "$R" | sed -r -e 's~\(~(*~g' -e 's~%~ *~g' -e 's~\)~)*~g' -e 's~^([A-Z]+)([0-9]+)~\1 *\2~')
      grep $1 "^.*;.*;$R;.*;.*$" ~terescoj/travelmapping/HighwayData/updates.csv \
      | sed -r -e "s~;$r;~;$e[1m$e[4m$e[31m$r$e[0m;~" -e "s~($green_keywords)~$e[1m$e[4m$e[32m\1$e[0m~g"
    done | sort -r
}
```

**gfm flavored**
```sh
get_res () {
    for R in $routes; do
      R=$(echo "$R" | sed -r -e 's~\(~(*~g' -e 's~%~ *~g' -e 's~\)~)*~g' -e 's~^([A-Z]+)([0-9]+)~\1 *\2~')
      grep $1 "^.*;.*;$R;.*;.*$" ~terescoj/travelmapping/HighwayData/updates.csv \
      | sed -r -e "s~;$r;~;*\`$r\`*;~" -e "s~($green_keywords)~**\1**~g"
    done | sort -r
}
```

**forum flavored**
```sh
get_res () {
    for R in $routes; do
      R=$(echo "$R" | sed -r -e 's~\(~(*~g' -e 's~%~ *~g' -e 's~\)~)*~g' -e 's~^([A-Z]+)([0-9]+)~\1 *\2~')
      grep $1 "^.*;.*;$R;.*;.*$" ~terescoj/travelmapping/HighwayData/updates.csv \
      | sed -r -e "s~;$r;~;[color=red][b][u]$r[/u][/b][/color];~" \
               -e "s~($green_keywords)~[color=green][b][u]\1[/u][/b][/color]~g"
    done | sort -r
}
```

## Main body
```sh
e=$(echo -e '\e')
green_keywords='[Dd]eleted|[Mm]erged|[Rr]edesignated|[Rr]enamed'
roots=$(cut -f4 -d';' logs/updatesinvalidroots.log | sort | uniq)
count=0; total=$(echo "$roots" | wc -w | tr -d ' '); \
for r in $roots; do
  ((++count))
  routes=$( \
    grep "^.*;.*;.*;$r;.*$" ~terescoj/travelmapping/HighwayData/updates.csv | cut -f3 -d';' \
    | sort | uniq | tr ' ' '%')
  res=$(get_res '-m 1')
  if [[ $(echo "$res" | wc -l | tr -d ' ') != 1 ]] \
  || [[ "$res" == *"$r"* ]] \
  || echo "$res" | egrep -v $green_keywords; then
    clear
    echo -e $count/$total": $r\n"
    echo "$res"
    echo -en '\nExpand (y/[n])? '
    read act
    if [[ $act = y ]]; then
      echo
      get_res '-e'
      echo -en '\n>>> PRESS ENTER <<<'
      read act
    fi
  fi
done
```

LOL OK time to take a break

**Comment by yakra** [comment]
One thing neither the siteupdate implementation nor the script to crawl thru invalidupdatesroots.log consider:
**Case insensitivity.**
If the root in updates.csv is `ks.ks254TrkElD`, [the link](https://travelmapping.net/hb/showroute.php?r=ks.ks254TrkElD) loads up in the HB perfectly fine, upper case notwithstanding.
But right now `ks.ks254TrkElD` is put in invalidupdatesroots.log, because of the caps.
* [ ] siteupdate needs to convert to lower case before checking `root_hash`.
* [ ] script needs to `grep -i`

**Comment by michihdeu** [comment]
We won't ever find issues like this: https://github.com/TravelMapping/HighwayData/pull/8113/files

**Comment by yakra** [comment]
**Before we get started...**

The script shows any entry with...
* \> 1 line of text (even obvious FPs; better safe than sorry), or
* *`Text like this`* ("Red", the offending root), or
* No **text like this** ("Green"-listed keywords suggesting "We might be good here").
* Lines with the same route name but a different or no root. These can help show routes that got deleted or merged.
  These get pulled from the master `systems.csv`, and might not be in invalidupdatesroots.log at all.

> 4/621: ab.ab201swc
> 
> 2024-01-01;(Canada) Alberta;AB 201 (Southwest Calgary);ab.ab201;**Merged** into main AB 201 route.
> 2021-10-03;(Canada) Alberta;AB 201 (South Calgary);*`ab.ab201swc`*;Route **deleted**. **Merged** into Southwest Calgary segment.
> 2020-10-02;(Canada) Alberta;AB 201 (Woodbine);*`ab.ab201swc`*;Route **deleted**. **Merged** into new Southwest Calgary segment.
> 2020-10-02;(Canada) Alberta;AB 201 (Signal Hill);*`ab.ab201swc`*;Route **deleted**. **Merged** into new Southwest Calgary segment.

This group is a pretty obvious FP.
The top line having **"green"** and no *`"red"`* text is more likely to mean we're fine.
OTOH if the top line does have *`"red"`*, something's probably wrong.

> 60/621: deumv.b096nbr
> 
> 2020-03-03;(Germany) Mecklenburg-Western Pomerania;B96 (Neubrandenburg);;Route removed

Probably fine; I just can't add `removed` to the "green list" because it's used in other contexts in updates.csv
Won't post any more like this if I see 'em.

> 13/621: ar.us071busfay
> 
> 2020-05-13;(USA) Arkansas;US 71 Business (Fayetteville);*`ar.us071busfay`*;Truncated at north end to Regional Airport Blvd in Bentonville (former western AR 12 junction)

`Fayetteville` vs `Fayetteville, AR` means its later renaming didn't show up in the search results.
This is either a less obvious FP, or a data error I should fix to be consistent about including state abbreviations.

---

Some entries can be "expanded" for more context.
Ask for an expansion if it seems like things aren't what they seem.

> 17/621: ausvic.a060
> 
> 2023-04-17;(Australia) Victoria;N1 Alternative (Melbourne);ausvic.n001altmel;Route added
> 2023-04-17;(Australia) Victoria;A60;;Route **deleted** (now N1Alt, MR60 and C101)
> 
> Expand (y/[n])? y

**Q:** Huh? Why's N1Alt listed? It has a different route name and root.

> Expand (y/[n])? y
> 
> 2023-04-17;(Australia) Victoria;N1 Alternative (Melbourne);ausvic.n001altmel;Route added
> 2023-04-17;(Australia) Victoria;A60;;Route **deleted** (now N1Alt, MR60 and C101)
> 2021-10-14;(Australia) Victoria;N1 Alternative (Melbourne);*`ausvic.a060`*;Route removed (now part of A60)
> 2021-10-14;(Australia) Victoria;A60;*`ausvic.a060`*;Route added (formerly N1Alt, MR60, and part of C101)
> 2015-08-25;Italy;A60;ita.a060;New Route

**A:** Because of unusual stuff in the history. It got associated with `ausvic.a060` when a previous N1Alt was deleted & merged. Now it's back from the dead, with the previous changes seemingly reverted.
LOL Italy.

> 48/621: cze.d048chl
> 
> 2022-12-24;Czechia;D48 (Frýdek-Místek);cze.d048;Route extended at west end from exit 52 east of Frýdek-Místek to II462 at Rybí
> 2022-12-24;Czechia;D48 (Chlebovice);cze.d048;Route **merged** into main route
> 2016-01-01;Czechia;R48 (Chlebovice);*`cze.d048chl`*;Route **renamed** D48 (Chlebovice)
> 
> Expand (y/[n])? y
> 
> 2022-12-24;Czechia;D48 (Frýdek-Místek);cze.d048;Route extended at west end from exit 52 east of Frýdek-Místek to II462 at Rybí
> 2022-12-24;Czechia;D48 (Chlebovice);cze.d048;Route **merged** into main route
> 2022-09-09;Czechia;D48 (Frýdek-Místek);*`cze.d048chl`*;Route **merged** into Chlebovice route
> 2022-09-09;Czechia;D48 (Chlebovice);*`cze.d048chl`*;Route extended at east end from exit 45A to exit 48
> 2022-07-03;Czechia;D48 (Frýdek-Místek);*`cze.d048chl`*;New Route
> 2019-12-18;Czechia;D48 (Chlebovice);*`cze.d048chl`*;Route extended at west end from exit 38 to II482
> 2016-01-01;Czechia;R48 (Chlebovice);*`cze.d048chl`*;Route **renamed** D48 (Chlebovice)

This one confuses me.

> 2017-06-01;Greece;A5 (Agrinio);grc.a005;Route extended at south end from temporary terminus at Riza to exit K7
> 2017-06-01;Greece;A5 (Patras);grc.a005;Route merged into Agrinio section

Same here. ISTM that "Agrinio" and "Patras" should be swapped between these 2.

---

## OK, Here goes...


> entries 22-31
> 2016-01-12;Belgium;E420 (Charleroi);*`bel.e420bel`*;New Route
> 2016-01-12;Belgium;Péripherique du Charleroi;*`bel.percha`*;New Route
> 2016-01-12;Belgium;Ring Antwerpen Oost;*`bel.ringante`*;New Route
> 2016-01-12;Belgium;Ring Antwerpen West;*`bel.ringantw`*;New Route
> 2016-01-12;Belgium;Ring Bruxelles / Ring Brussels;*`bel.ringbru`*;New Route
> 2016-01-12;Belgium;Ring Charleroi;*`bel.ringcha`*;New Route
> 2016-01-12;Belgium;Ring Gent Oost;*`bel.ringgento`*;New Route
> 2016-01-12;Belgium;Ring Kortrijk;*`bel.ringkor`*;New Route
> 2016-01-12;Belgium;Ring Mons Est;*`bel.ringmonse`*;New Route
> 2016-01-12;Belgium;Ring Mons Ouest;*`bel.ringmonso`*;New Route

Maybe something happened that affected a whole bunch of routes or a whole system under one big umbrella updates entry?
ISTR something like that for the DEU split.

> 38/621: che.a020gam
> 2021-01-31;Switzerland;Autostrasse Gals - Ins;*`che.a020gam`*;Route **deleted** (A20 (Gampelen) now)
> 
> 46/621: cze.d004pre
> 2016-01-01;Czechia;R4 (Predotice);*`cze.d004pre`*;Route **renamed** D4Pre
> 
> 49/621: cze.i004mil
> 2024-12-17;Czechia;I4 (Milín);cze.ii604;Route mostly **merged** into II604
> 2017-10-08;Czechia;I4;*`cze.i004mil`*;Route truncated at norht end from D4 exit 41 to exit 45
> 
> 56/621: deubw.e54lor
> 2015-09-15;(Germany) Baden-Württemberg;E54;*`deubw.e54lor`*;Route relocated from Nollinger Strasse and B34 to B316 between Nollinger Strasse and the B34/B316 junction
> 2015-09-15;(Germany) Baden-Württemberg;E54;*`deubw.e54lor`*;Route relocated from L154 to A98 between A98 exits 11 and 13
> 
> 74/621: deusn.b172n
> 2022-12-24;(Germany) Saxony;B172n;deusn.b172n;New Route
> 
> 80/621: dnk.silmot
> 2015-10-17;Denmark;Silkeborgmotorvejen;*`dnk.silmot`*;New Route

A lot of the script's results are pre-split ESP & FRA entries.
No results for old DEU routes though. What's the sory there?

> 2019-08-02;France;N4;*`fraidf.n004`*;Route extended at west end from N104 to D604

The root itself is fine because it was downgraded later, but `France` -> `(France) Île-de-France` ?

Some entries from anybody/everybody/nobody regions, in case you wanna have a look at`em :)
> 282/621: grc.a001ath
> 2015-08-20;Greece;A1 (Athens);*`grc.a001ath`*;Route extended at south end from exit 82 to exit 87
> 2015-08-20;Greece;A1 (Athens);*`grc.a001ath`*;Route extended at north end from exit 43 to PE01
> 
> entries 354-356
> 2021-11-21;Iran;AH2 (Tehran (spur));*`irn.ah002teh`*;Route added
> 2021-11-21;Iran;F5 (Arak);*`irn.f002ara`*;Route added
> 2021-11-21;Iran;F5 (Borujerd);*`irn.f002bor`*;Route added

> 385/621: mkd.a004sko
> 2019-04-17;North Macedonia;A4 (Skopje);*`mkd.a004sko`*;Route **deleted** (**merged** into main section)

`2018-09-09;Netherlands;` entries look off; could use rewording.

> 411/621: nor.rv041krl
> 2020-04-09;Norway;Rv451;*`nor.rv041krl`*;Route **deleted** (Rv41 now)
> 2020-04-09;Norway;Rv41 (Kristiansand Lufthavn(;*`nor.rv041krl`*;New Route (former Rv451)
> 
> 412/621: nor.rv042
> 2017-02-12;Norway;Rv42;*`nor.rv042`*;New Route

> 420/621: nor.rv881
> 2020-04-05;Norway;Rv881;nor.e6alt;Route removed (E6 now)

`nor.e6alt` is valid; just commenting that it might be clearer to say "E6 (Alta lufthavn)" rather than require the user to click on the link to find out.`
Seems I've seen a few of these worldwide, but haven't been keeping track till now.

> 535/621: prt.a008_1
> 2023-03-07;Portugal;A8-1;prt.a0081;Route extended at north end from exit 2 to IC2
> 2015-12-02;Portugal;A8-1;*`prt.a008_1`*;New Route
> 
> 536/621: prt.a026_1
> 2023-03-07;Portugal;A26-1;prt.a0261;Route truncated at north end from exit 3 to exit 2
> 2017-04-21;Portugal;A26-1;*`prt.a026_1`*;New Route

Were these roots valid at the time A8-1 & A26-1 were created?
(Been thinking a while how in some cases delimiters like these might actually be justified in roots, but that's off-topic.)

> 576/621: swe.aliled
> 2016-08-08;Sweden;Alingsåsleden;*`swe.aliled`*;New Route
> 
> 578/621: swe.inreringvag
> 2016-05-01;Sweden;Malmo Inre Ringvagen;*`swe.inreringvag`*;New Route
> 
> 580/621: swe.lundlinmot
> 2017-12-20;Sweden;Lund - Linderöd motorvägen;*`swe.lundlinmot`*;Route extended at east end from exit "Trafikplats Linderöd Väst" to exit "Trafikplats Spangårp"
> 
> 582-584
> 2016-09-02;Sweden;Toftaholm - Jönköping motorvägen;*`swe.tofjonmot`*;New Route
> 2016-05-01;Sweden;Vätterleden;*`swe.vatled`*;New Route
> 2016-05-01;Sweden;Malmo Yttre Ringvagen;*`swe.yttringvag`*;New Route

**Comment by michihdeu** [comment]
- Is this the full list for updates.csv entries of my regions? I'll look into them tomorrow.
- I'm confused by the **bold** words. Do you think about some magic if **deleted**, **renamed** or **merged** is used? We have no rule for update entries. I was about to suggest a rule but there was a huge opposition.... Bad memories from the past dictatorship....
- Is there any direct question to me?

- Colors? I thought we'd output to a simple log file.
> "Red"
> "Green"

- Why systems.csv? Typo?
> These get pulled from the master systems.csv

**Comment by michihdeu** [comment]
> LOL Italy.

Still waiting for the MVP 😉 

> No results for old DEU routes though. What's the sory there?

I think I've cleaned them up.

**Comment by yakra** [comment]
Oops sorry, forgot to start off that last post with,
> Grr, I don't like that I can't do colored text on GitHub.
> The script that crawls thru invalidupdatesroots.log color-codes its output in the terminal. If I were posting this in the forum instead, there'd be red & green text.
> Instead, here on GitHub, imagine that...
> * *`this stuff is red`*
> * **this stuff is green**

It just helps to get a visual on the script results and parse it quickly.

> - Colors? I thought we'd output to a simple log file.

So yes, invalidupdatesroutes.log will be just a simple log, plain ascii text.

---

**To clarify...**
There are 2 separate programs coming into play in my last several posts:
* The actual siteupdate implementation itself.
  Very simple. We already ask the question, [Does this root point to a Route object in `root_hash`?](https://github.com/TravelMapping/DataProcessing/blob/12f8df81ff3c52ad9109492fc11256756265f837/siteupdate/cplusplus/tasks/read_updates.cpp#L56)
  Only new bit is, now [when the answer is No](https://github.com/TravelMapping/DataProcessing/blob/12f8df81ff3c52ad9109492fc11256756265f837/siteupdate/cplusplus/tasks/read_updates.cpp#L60), write the updates.csv line to invalidupdatesroots.log.
* The gnarly-ass [shell](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-2614534651) [script](https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-2614579033) used for crawling thru the log file, focusing on invalid roots that may need fixing, ignoring stuff that can be safely ignored, and displaying more gray-area cases so a human can make the call.
This is way more complicated, and won't affect siteupate itself.
It's just a 1-time thing to find my stuff to fix, your stuff for me to paste in here, and maybe everybody else's stuff for a forum post when this goes live. (I guess maybe that makes it a 3-time thing? :rofl:)

---

> - Is this the full list for updates.csv entries of my regions? I'll look into them tomorrow.

Pretty much, yes. (Other than that one thing I said I hadn't kept track of?)
It's the stuff that looks iffy.
Some of the results made obvious sense, like if something later got deleted or merged into another route. I didn't paste these in.

> - I'm confused by the **bold** words. Do you think about some magic if **deleted**, **renamed** or **merged** is used? We have no rule for update entries. I was about to suggest a rule but there was a huge opposition.... Bad memories from the past dictatorship....

These keywords weren't used in the siteupdate implementation at all.
(So, I don't propose any changes to the existing way we've been doing updates.csv.)
They were highlighted **green** by the shell script, just for purposes of quickly indicating potential FPs, invalid roots that can be safely ignored.

> - Is there any direct question to me?

No overall questions or anything I'm seeking clarification on.
Just the individual questions about small groups of entries in the post above.

One more thing I left out --
A lot of stuff may be flagged because an old `root` is correct, for a route that got deleted, but there was no subsequent updates entry indicating it got deleted. Nothing the script found, at least.

> - Why systems.csv? Typo?
>> These get pulled from the master systems.csv

Typo/brainfart, yes. Should say `updates.csv`.

---

>> LOL Italy.

LOL, I just meant that in the sense of "O HAY look that that unrelated country crapping up the search results!"

> Still waiting for the MVP 😉 

Hey now, whaddaya want me working on more, this or that?? :rofl: LOLJK

To be serious, I think when I was most recently on the forum, I posted re that, linking to the "let's work the ITA split out here" thread, noting it hadn't been updated.
I hope to be back to the forum again soon, and can see if that topic's been updated.

WRT an MVP of *siteupdate's hidden system support*, it's mostly in place, but finishing it off should happen concurrently with getting HighwayData sorted for the ITA split. That will bring into clearer focus what needs to be tweaked before going live.

>> A lot of the script's results are pre-split ESP & FRA entries.
>
> Please don't make it too complicated... keep it simple. MVP mode......

Right, nothing in siteupdate or the shell script takes this into account.
Just commenting on it, thankful that there's lots of stuff with a clear explanation, stuff I can `>>> PRESS ENTER <<<` on through while running the shell script, and ignore.

>> No results for old DEU routes though. What's the sory there?
>
> I think I've cleaned them up.

Ah. I woulda thought , keep'em around for historical purposes, but \*shrug\*. What's done is done.
_In a sense,_ travelers were starting over with new split routes for the new split regions, lol.

**Comment by michihdeu** [comment]
>  I hope to be back to the forum again soon, and can see if that topic's been updated.

I think that Si fixed everything: https://github.com/TravelMapping/HighwayData/pull/8062/commits/0da832f71b977d97c8095d0c8828328d6d19b9eb

**Comment by michihdeu** [comment]
> This one confuses me.

The Czech I48 was (and still is) being upgraded to motorway standard piece by piece.

> >2017-06-01;Greece;A5 (Agrinio);grc.a005;Route extended at south end from temporary terminus at Riza to exit K7
> >2017-06-01;Greece;A5 (Patras);grc.a005;Route merged into Agrinio section

> Same here. ISTM that "Agrinio" and "Patras" should be swapped between these 2.

I don't get it. I think it's fine as-is.

Why was that not found?
`2015-08-20;Greece;A1 (Kato Egani);grc.a001kat`

> A lot of the script's results are pre-split ESP & FRA entries.

Only 23 French update entries left.... the eursf ones.... tomorrow...
I hope that I haven't fukced up the French entries.... does data check check it? Or is there a log of invalid number of lines or invalid field content? 😆 😆 😆

**Comment by michihdeu** [comment]
> Only 23 French update entries left.... the eursf ones.... tomorrow...

Done. @yakra If you want, you could post my regions again 😄
